### PR TITLE
checker: add EqualsIn checker

### PR DESCRIPTION
**Pull request by MrCroxx**
EuqalsIn checker returns true when obtained value equals one of the expected values in the given interface slice.

Signed-off-by: MrCroxx <mrcroxx@outlook.com>

### CODE REVIEW

**Comment by MrCroxx** [comment]
@zimulala PTAL

**Review by zimulala — COMMENTED** [review]
LGTM

**Comment by MrCroxx** [comment]
@zimulala  Cloud you help merge this pr?

**Comment by zimulala** [comment]
PTAL @tiancaiamao

**Review by tiancaiamao — APPROVED** [review]

**Pull request merged**
